export const SET_FILTERS = 'SET_FILTERS';
export const SET_SEARCH_PHRASE = 'SET_SEARCH_PHRASE';

export const SET_CATALOG_ITEMS = 'SET_CATALOG_ITEMS';

export const SET_SUB_FILTERS_ITEM = 'SET_SUB_FILTERS_ITEM';
